In [1]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created using pandas list:\n",a)

Array created using pandas list:
 [[1 2 4]
 [5 8 7]]


In [2]:
import numpy as np
b=np.zeros((3,4))
print("\nAn array initialized with all zeros:\n",b)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
import numpy as np
c=np.full((3,3),6)
print("An array initialized with all 6s.\n",c)

An array initialized with all 6s.
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [4]:
import numpy as np
d=np.random.random((2,2))
print("\nA random array:\n",d)


A random array:
 [[0.75689229 0.67754769]
 [0.57765203 0.61227614]]


In [6]:
import numpy as np
e=np.arange(0,30,5)
print("\nA sequential array with steps of 5:\n",e)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [7]:
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\nOriginal array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [8]:
import numpy as np
flarr=arr.flatten()
print("\nOriginal array:\n",arr)
print("Fattened array:\n",flarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Fattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [9]:
import numpy as np
print("\nNo.of dimensions:",arr.ndim)


No.of dimensions: 2


In [10]:
import numpy as np
print("\nShape of array:",arr.shape)


Shape of array: (3, 4)


In [11]:
import numpy as np
print("\nSize of array:",arr.size)


Size of array: 12


In [12]:
import numpy as np
print("\nArray stores elements of type:",arr.dtype)


Array stores elements of type: int32


In [14]:
import numpy as np
newtype=arr.astype('f')
print("\nConverted array elements:\n",newtype)
print("Converted array type:",newtype.dtype)


Converted array elements:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
Converted array type: float32


In [15]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]]) 
print("original array:\n",arr)
print("\nevery other rows:arr[0:3:2]:\n",arr[0:3:2])

original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]

every other rows:arr[0:3:2]:
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [16]:
import numpy as np
temp=arr[:2,:3]
print("\nArray with first 2 rows and 3 columns:arr[:2,:3]:\n",temp)


Array with first 2 rows and 3 columns:arr[:2,:3]:
 [[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [39]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]]) 
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\nElements at indicies (0,3),(1,2),(2,1)(3,0):\n",temp)


Elements at indicies (0,3),(1,2),(2,1)(3,0):
 [4. 6. 0. 3.]


In [40]:
import numpy as np
cond=arr>2
temp=arr[cond]
print("\nElements greater than 2:\n",temp)


Elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]


In [38]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print("\nOriginal array:",arr)
print("\nReturns every other elements in the array:arr:[::2]:",arr[::2])


Original array: [1 2 3 4 5 6 7]

Returns every other elements in the array:arr:[::2]: [1 3 5 7]


In [23]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print("\nOriginal arrays:\n",arr1,arr2)
print("\nJoined array:\n",arr)


Original arrays:
 [1 2 3] [4 5 6]

Joined array:
 [1 2 3 4 5 6]


In [24]:
import numpy as np
arr=np.hstack((arr1,arr2))
print("\nHorizontal joining:\n",arr)


Horizontal joining:
 [1 2 3 4 5 6]


In [25]:
import numpy as np
arr=np.vstack((arr1,arr2))
print("\nVertical joining:\n",arr)


Vertical joining:
 [[1 2 3]
 [4 5 6]]


In [26]:
import numpy as np
arr=np.dstack((arr1,arr2))
print("\nDepth joining:\n",arr)


Depth joining:
 [[[1 4]
  [2 5]
  [3 6]]]


In [27]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print("\nOriginal array:\n",arr)
print("\nSplitted array:\n",newarr)


Original array:
 [1 2 3 4 5 6]

Splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]


In [28]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print("\nSplitted array in another ofrm:\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])


Splitted array in another ofrm:

[1 2]
[3 4]
[5 6]


In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
print("original array:",arr)
x=np.where(arr==4)
print("\nindexes where the value is 4:",x)

original array: [1 2 3 4 5 4 4]

indexes where the value is 4: (array([3, 5, 6], dtype=int64),)


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print("\noriginal array:",arr)
print("\nindexes where the values are even:",x)


original array: [1 2 3 4 5 6 7 8]

indexes where the values are even: (array([1, 3, 5, 7], dtype=int64),)


In [3]:
import numpy as np
x=np.searchsorted(arr,3,side='left')
print("\nindexes where the value 3 should be inserted, starting from the right:",x)


indexes where the value 3 should be inserted, starting from the right: 2


In [4]:
import numpy as np
arr=np.array([3,2,0,1])
print("\noriginal array:",arr)
print("\nsorted array:",np.sort(arr))


original array: [3 2 0 1]

sorted array: [0 1 2 3]


In [5]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print("\nOriginal array:",arr)
print("\nSorted array:",np.sort(arr))


Original array: [[3 2 4]
 [5 0 1]]

Sorted array: [[2 3 4]
 [0 1 5]]


In [6]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x)
print("\nFilter array:",newarr)


Original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filter array: [41 43]


In [7]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print("\nOriginal array:",arr)
print("\nFilter array:condition- >42:",filter_arr)
print("\nNew array:",newarr)


Original array: [41 42 43 44]

Filter array:condition- >42: [False False  True  True]

New array: [43 44]


In [9]:
arr1=[10,20,30,40,50] 
arr2=[2,4,5,8,10]
a=np.array(arr1)
b=np.array(arr2)
print("Original arrays")
print(a) 
print(b)

print("\nVector addition")
print(a+b)

Original arrays
[10 20 30 40 50]
[ 2  4  5  8 10]

Vector addition
[12 24 35 48 60]


In [10]:
arr1=[10,20,30,40,50] 
arr2=[2,4,5,8,10]
a=np.array(arr1)
b=np.array(arr2)
print("Original arrays")
print(a) 
print(b)
print("\nVector subtraction")
print(a-b)

Original arrays
[10 20 30 40 50]
[ 2  4  5  8 10]

Vector subtraction
[ 8 16 25 32 40]


In [11]:
print("\nVector multiplication")
print(a*b)


Vector multiplication
[ 20  80 150 320 500]


In [12]:
print("\nVector division")
print(a/b)


Vector division
[5. 5. 6. 5. 5.]


In [13]:
print("\nVector Dot product")
print(a.dot(b))


Vector Dot product
1070


In [14]:
print("\nScalar multiplication")
sclr=5
print(" scalar value=",sclr)
print(" array=",a)
print(" result=",a*sclr)


Scalar multiplication
 scalar value= 5
 array= [10 20 30 40 50]
 result= [ 50 100 150 200 250]
